### ISSUE TITLE
Add support for multiple line password hash file

### ISSUE THREAD

**Issue by BoxHezi** [AnataarXVI/Werkzeug-Cracker#2]
Hi, first of all, thanks for this awesome cracker. During the use, I discovered one problem.

## Problem

When I have a password hash file with multiple lines, each line is a password hash to crack.
The program only crack the first line.

The reason is in the `__init__` function of `Werkzeug_Cracker`, it only set the `self.hash = hash[0]` where `hash` is a list.
So even if multiple hashes are loaded, it will only crack the first one.

## Fix

Are you open to contribution? I have forked the project and apply fix to this problem. If so, I can open a PR.

Thanks again,
Box

**Comment by AnataarXVI** [comment]
Hi, thanks for your feedback! I'm open to contributions.

I've looked at the modifications you've made. It's good work. I tested the tool by trying to indicate a file containing several passwords. The tool seems to work correctly. However, I've noticed a problem when the tool cracks the second password, it doesn't restart the wordlist from the beginning. 

 ## Fix 

I managed to fix the problem this way :

```python
else:
        ## Open the wordlist
        with open(args.wordlist, "r", encoding="latin-1") as wordlist:
            raw_words = wordlist.read().split()

        ## Open the hash file
        with open(args.password,"r") as phash:
            hashes = phash.read().split()

        ## Initialize
        for h in hashes:
            ## Initialize the Queue
            words = Queue()

            ## Increment the Queue with passwords of the wordlist
            for word in raw_words:
                words.put(word)

            cracker = Werkzeug_Cracker(h, words, args.threads)
            cracker.start()
            cracker.join()
        # Werkzeug_Cracker(hash, words, args.threads)
        # for i in range(len(hashes)):
        #     Werkzeug_Cracker(hashes[i], words, args.threads)

```

If you think there's a better way, don't hesitate.

Once you've solved the problem, feel free to open a pull request :)

Anataar

**Comment by BoxHezi** [comment]
Hi, thanks for the reply. I can replicate the problem you mentioned.

My approach to solve the problem is similar as yours. Instead of creating a `queue.Queue()` for each hash, I use `copy.copy()` to clone the wordlist. One other problem I met is that `queue.Queue()` doesn't support `copy.copy()`, so I have to use `collections.deque()` instead. But in this case, I will have make more modification to retrieve items from `deque` (i.e. change `q.get()` to `q.popleft()`, etc.)

```python
else:
        ## Open the wordlist
        with open(args.wordlist, "r", encoding="latin-1") as wordlist:
            raw_words = wordlist.read().split()

            ## Initialize the Queue
            words = deque()

            ## Increment the Queue with passwords of the wordlist
            for word in raw_words:
                words.append(word)

        ## Open the hash file
        with open(args.password, "r") as phash:
            hashes = phash.read().split()

        ## Initialize
        for h in hashes:
            cracker = Werkzeug_Cracker(h, copy(words), args.threads)
            cracker.start()
            cracker.join()
```

I don't know which solution is the better one. From my testing, both yours and mine can solve the problem we've mentioned, and I don't see much performance difference between these two solutions. But to keep less modification, I am going to go with your solution.

FYI: I also create two files, `example.hash` contains password hashes, `example.lst` contains passwords. The `example.lst` is created from rockyou. Just for the ease of testing. :)

Box

**Comment by AnataarXVI** [comment]
pull request validated !
